### ISSUE TITLE
Accessibility improvement ideas

### ISSUE THREAD

**Issue by DorienHuijser** [UtrechtUniversity/privacy-engineering-tools#7]
Ideas to improve this repo's accessibility/understandability:

- Create a github pages website (later)
- Create an index.md in every subfolder that shortly describes what the folder is about and link to relevant section in the [Data Privacy Handbook](https://uu.nl/privacyhandbook)
- Add the date of last edit in every file for transparency

**Comment by qubixes** [comment]
I feel like perhaps the last item (last edit time) is not really so useful, given that it is already available in git/GitHub. Also, just because we edited it, doesn't mean it's up-to-date, unless we recheck every entry. Would be a great case for a bot!
