### ISSUE TITLE
Look into pseudonymisation tool Spider.Erdri

### ISSUE THREAD

**Issue by DorienHuijser** [UtrechtUniversity/privacy-engineering-tools#8]
In my Slack inbox:

<blockquote>Recently, for this domain [rare diseases], a pseudonymisation tool called [Spider.Erdri](https://eu-rd-platform.jrc.ec.europa.eu/spider/) was developed. The plus of the tool is that it generates pseudonyms for patients and allows linkage and transferring patient data across multiple registries (this is relevant because sometimes the same patient is in different registries). The downside is that registries need to upload data on erdri in order to use the tool - it's a downside because there are already different tools in place, and it makes them not interested in using yet another tool. I am texting you because from what I saw on the git repository, there isn't any "spider like" tool that could be incorporated with already existing methodologies, but I would love to know if you have knowledge of another alternative that I could give a look!</blockquote>

So to do:
- Check out this specific tool
- Look into other "spider-like" tools that would be an alternative to this tool

**Comment by qubixes** [comment]
Personally, I feel like it's not really a tool in the traditional sense, maybe it's more like a platform? It's also quite specific to the ERDRI it seems? I'm not sure where to put it, but they call themselves a pseudonymisation tool, so I guess it goes there.
